name: bubunta

on: [push]

jobs:
  focal:
      name: gcc
      runs-on: ubuntu-latest
      container:
        image: ubuntu:20.04
      steps:
        - uses: actions/checkout@master
        - name: hello world
          run: |
            cat /proc/version
            dpkg -l
            cat /etc/issue

